server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
    context-path: '/'

spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    log-sql: true
    password: admin
    url: jdbc:mysql://localhost:3306/desbravador?useTimezone=true&serverTimezone=UTC
    username: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
      generate-ddl: true
    show-sql: true




logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always